### A MNIST-like fashion product database

In this, we classify the images into respective classes given in the dataset. We use a Neural Net and a Deep Neural Net in Keras to solve this and check the accuracy scores.

### Load tensorflow

In [0]:
import tensorflow as tf
tf.set_random_seed(42)

import numpy as np
import pandas as pd
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense,Dropout,Activation,Flatten
from keras.layers.convolutional import Conv2D,MaxPooling2D
from keras import optimizers
from keras.utils import np_utils
from sklearn import metrics
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
tf.__version__

'1.14.0'

### Collect Data

In [0]:
(trainX, trainY), (testX, testY) = keras.datasets.fashion_mnist.load_data()

In [7]:
print(testY[0:5])

[9 2 1 1 6]


### Convert both training and testing labels into one-hot vectors.

**Hint:** check **tf.keras.utils.to_categorical()**

In [0]:
from keras.utils import to_categorical

In [0]:
trainX.shape

(60000, 28, 28)

In [10]:
trainY.shape

(60000,)

In [11]:
#Displaying the values in different categories
L=pd.DataFrame(trainY)
L[0].value_counts()

9    6000
8    6000
7    6000
6    6000
5    6000
4    6000
3    6000
2    6000
1    6000
0    6000
Name: 0, dtype: int64

In [0]:
#Represent Training & Testing samples suitable for 
#tensorflow backend
x_train=trainX.reshape(trainX.shape[0],28,28,1).astype('float32')
x_test=testX.reshape(testX.shape[0],28,28,1).astype('float32')
#for theano (1,28,28), for tensorflow (28,28,1)

In [14]:
x_train.shape

(60000, 28, 28, 1)

In [0]:
x_train/=255
x_test/=255

In [16]:
#Encoding the output class label (One-Hot Encoding)
y_train=np_utils.to_categorical(trainY,10)
y_test=np_utils.to_categorical(testY,10)
y_train[2]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

### Visualize the data

Plot first 10 images in the triaining set and their labels.

In [0]:
import matplotlib.pyplot as plt

for x in range(0, 10):
  first_array=trainX[x]
  plt.imshow(first_array)
  plt.show()
  plt.savefig("fig.png")
  print("This image belongs to Category : ", trainY[x])

### Build a neural Network with a cross entropy loss function and sgd optimizer in Keras. The output layer with 10 neurons as we have 10 classes.

In [45]:
model=Sequential()
model.add(Conv2D(32,(3,3),border_mode='valid',input_shape=(28,28,1),activation='relu'))
model.add(Flatten())
model.add(Dense(10,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(28, 28, 1..., activation="relu", padding="valid")`
  


### Execute the model using model.fit()

In [46]:
model.fit(x_train,y_train,batch_size=200,nb_epoch=12,verbose=1,validation_data=(x_test,y_test))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 3s 51us/step - loss: 0.9403 - acc: 0.7034 - val_loss: 0.6518 - val_acc: 0.7755
Epoch 2/12
60000/60000 [==============================] - 3s 43us/step - loss: 0.6047 - acc: 0.7896 - val_loss: 0.5821 - val_acc: 0.7895
Epoch 3/12
60000/60000 [==============================] - 2s 41us/step - loss: 0.5571 - acc: 0.8034 - val_loss: 0.6762 - val_acc: 0.7415
Epoch 4/12
60000/60000 [==============================] - 2s 41us/step - loss: 0.5315 - acc: 0.8135 - val_loss: 0.5146 - val_acc: 0.8168
Epoch 5/12
60000/60000 [==============================] - 2s 41us/step - loss: 0.5108 - acc: 0.8205 - val_loss: 0.5327 - val_acc: 0.8058
Epoch 6/12
60000/60000 [==============================] - 2s 41us/step - loss: 0.4966 - acc: 0.8262 - val_loss: 0.5124 - val_acc: 0.8175
Epoch 7/12
60000/60000 [==============================] - 2s 41us/step - loss: 0.4834 - acc: 0.8313 - val_loss: 0.4994 - val_acc

### In the above Neural Network model add Batch Normalization layer after the input layer and repeat the steps.

In [0]:

model1=tf.keras.models.Sequential()
#model.add(Conv2D(32,(3,3),border_mode='valid',input_shape=(28,28,1),activation='relu'))
#Normalize input data
model1.add(tf.keras.layers.BatchNormalization(input_shape=(28,28,1)))

model1.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])

### Execute the model

### Customize the learning rate to 0.001 in sgd optimizer and run the model

In [0]:
from keras import optimizers

In [48]:
model=Sequential()
model.add(Conv2D(32,(3,3),border_mode='valid',input_shape=(28,28,1),activation='relu'))
model.add(Flatten())
model.add(Dense(10,activation='softmax'))

sgd = optimizers.SGD(lr=0.001, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',optimizer='sgd',metrics=['accuracy'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(28, 28, 1..., activation="relu", padding="valid")`
  


In [49]:
model.fit(x_train,y_train,batch_size=200,nb_epoch=12,verbose=1,validation_data=(x_test,y_test))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 3s 49us/step - loss: 0.9413 - acc: 0.7029 - val_loss: 0.6585 - val_acc: 0.7593
Epoch 2/12
60000/60000 [==============================] - 2s 41us/step - loss: 0.5979 - acc: 0.7900 - val_loss: 0.5649 - val_acc: 0.8035
Epoch 3/12
60000/60000 [==============================] - 2s 41us/step - loss: 0.5533 - acc: 0.8048 - val_loss: 0.5487 - val_acc: 0.8018
Epoch 4/12
60000/60000 [==============================] - 3s 42us/step - loss: 0.5238 - acc: 0.8157 - val_loss: 0.5448 - val_acc: 0.8011
Epoch 5/12
60000/60000 [==============================] - 3s 42us/step - loss: 0.5092 - acc: 0.8212 - val_loss: 0.5213 - val_acc: 0.8140
Epoch 6/12
60000/60000 [==============================] - 2s 42us/step - loss: 0.4949 - acc: 0.8272 - val_loss: 0.4927 - val_acc: 0.8260
Epoch 7/12
60000/60000 [==============================] - 2s 42us/step - loss: 0.4843 - acc: 0.8330 - val_loss: 0.4866 - val_acc

### Build the Neural Network model with 3 Dense layers with 100,100,10 neurons respectively in each layer. Use cross entropy loss function and singmoid as activation in the hidden layers and softmax as activation function in the output layer. Use sgd optimizer with learning rate 0.03.

In [50]:
model=Sequential()
model.add(Conv2D(32,(3,3),border_mode='valid',input_shape=(28,28,1),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(100,activation='sigmoid'))
model.add(Dense(100,activation='sigmoid'))
model.add(Dense(10,activation='sigmoid'))
model.add(Dense(10,activation='softmax'))
sgd = optimizers.SGD(lr=0.03, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(28, 28, 1..., activation="relu", padding="valid")`
  
W0724 20:03:19.061075 139915748571008 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



## Review model

### Run the model

In [51]:
model.fit(x_train,y_train,batch_size=200,nb_epoch=12,verbose=1,validation_data=(x_test,y_test))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Train on 60000 samples, validate on 10000 samples
Epoch 1/12
60000/60000 [==============================] - 4s 66us/step - loss: 1.5547 - acc: 0.5790 - val_loss: 1.0960 - val_acc: 0.7767
Epoch 2/12
60000/60000 [==============================] - 3s 53us/step - loss: 0.8980 - acc: 0.8071 - val_loss: 0.7574 - val_acc: 0.8223
Epoch 3/12
60000/60000 [==============================] - 3s 52us/step - loss: 0.6552 - acc: 0.8500 - val_loss: 0.5862 - val_acc: 0.8609
Epoch 4/12
60000/60000 [==============================] - 3s 52us/step - loss: 0.5072 - acc: 0.8840 - val_loss: 0.4766 - val_acc: 0.8834
Epoch 5/12
60000/60000 [==============================] - 3s 51us/step - loss: 0.4180 - acc: 0.8975 - val_loss: 0.4102 - val_acc: 0.8931
Epoch 6/12
60000/60000 [==============================] - 3s 52us/step - loss: 0.3587 - acc: 0.9077 - val_loss: 0.3768 - val_acc: 0.8947
Epoch 7/12
60000/60000 [==============================] - 3s 52us/step - loss: 0.3132 - acc: 0.9163 - val_loss: 0.3474 - val_acc

In [52]:
score=model.evaluate(x_test,y_test)
score

10000/10000 [==============================] - 1s 74us/step


[0.286895356965065, 0.9058]

In [0]:
y_predict = model.predict(x_test)

In [54]:
y_predict[0]

array([2.2234250e-05, 4.2360919e-03, 2.5680862e-04, 1.9906939e-03,
       1.5238606e-03, 8.5243251e-04, 5.0946599e-04, 2.3164630e-02,
       2.0491211e-04, 9.6723884e-01], dtype=float32)

In [55]:
np.argmax(y_predict[0])

9

In [56]:
y_pred = []
for val in y_predict:
    y_pred.append(np.argmax(val))
#print(y_pred)    
#convert 0 1 to 1 and 1 0 as 0
cm = metrics.confusion_matrix(testY,y_pred)
print(cm)

[[834   0  10  16   3   1 120   0  16   0]
 [  1 976   2  17   1   0   2   0   1   0]
 [ 15   0 863   6  38   0  78   0   0   0]
 [ 15   1   7 913  29   0  32   0   2   1]
 [  1   0  85  26 823   0  65   0   0   0]
 [  0   1   0   0   0 981   0  13   1   4]
 [ 98   1  66  22  47   0 760   0   6   0]
 [  0   0   0   0   0  17   0 963   0  20]
 [  2   1   3   6   0   2   2   2 982   0]
 [  0   0   0   0   0   6   1  29   1 963]]


In [57]:
cr=metrics.classification_report(testY,y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.86      0.83      0.85      1000
           1       1.00      0.98      0.99      1000
           2       0.83      0.86      0.85      1000
           3       0.91      0.91      0.91      1000
           4       0.87      0.82      0.85      1000
           5       0.97      0.98      0.98      1000
           6       0.72      0.76      0.74      1000
           7       0.96      0.96      0.96      1000
           8       0.97      0.98      0.98      1000
           9       0.97      0.96      0.97      1000

    accuracy                           0.91     10000
   macro avg       0.91      0.91      0.91     10000
weighted avg       0.91      0.91      0.91     10000

